services:
  frontend:
    build: ./some-webapp
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3006

  backend:
    build: ./some-backend
    ports:
      - "3006:3006"