services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - app-net

  backend:
    build: ./some-backend
    ports:
      - "3001:3006"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - app-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  webapp:
    build: ./some-webapp
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: http://backend:3006
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    name: some-network

volumes:
  pgdata:
